name = "kilterboardie-api"
main = "index.js"
compatibility_date = "2024-11-01"

[vars]
DATA_REPO_OWNER = "Pa-Sto"
DATA_REPO_NAME = "kilterboardie-feedback"
DATA_REPO_BRANCH = "main"
ALLOWED_ORIGINS = "https://pa-sto.github.io"
